### ISSUE TITLE
Bug in loop at line 693

### ISSUE THREAD

**Issue by coseltech** [vaeth/find_cruft#2]
On my Perl 5.24.3 (x86_64) false positives result from the fact that the loop on line 693 is not entered for some files. I have resolved this by changing the loop to
`for my $j (0 .. $#$i) {
  $s = @$i[$j];
...`

I don't know why this works. Could there be a bug in the Perl implementation ?

**Comment by vaeth** [comment]
“each” in array context for arrays works only since perl-5.12.
Since the code claims to be compatible with perl-5.8, this was a bug in any case.

This issue should now be fixed in the new release 5.1.
Let us hope that your problem vanishes with this.
